<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IaphubPackageVersion Condition="'$(IaphubPackageVersion)' == ''">1.1.3</IaphubPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(IaphubExampleUseNuget)' != 'true'">
    <ProjectReference Include="../../src/Iaphub/Iaphub.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(IaphubExampleUseNuget)' == 'true'">
    <PackageReference Include="Iaphub" Version="$(IaphubPackageVersion)" />
  </ItemGroup>
</Project>
