<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <IaphubPackageVersion Condition="'$(IaphubPackageVersion)' == ''">1.1.2</IaphubPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(IaphubExampleUseNuget)' != 'true'">
    <ProjectReference Include="..\..\..\src\Iaphub\Iaphub.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(IaphubExampleUseNuget)' == 'true'">
    <PackageReference Include="Iaphub" Version="$(IaphubPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Iaphub.Example.Shared\Iaphub.Example.Shared.csproj" />
  </ItemGroup>
</Project>
